---
# tasks file for acme-tiny-install/
- name: test for an installation by the distro in /bin
  stat:
    path: "/bin/acme-tiny"
  register: acme_tiny__bin

- name: test for an installation by the distro in /usr/bin
  stat:
    path: "/usr/bin/acme-tiny"
  register: acme_tiny__usrbin
  when: acme_tiny__bin.stat.isreg is not defined or not acme_tiny__bin.stat.isreg

- name: manually install acme-tiny
  environment:
    http_proxy: "{{ http_proxy }}"
  get_url:
    checksum: "{{ app__acme__tiny__checksum }}"
    dest: "/usr/local/bin/acme-tiny"
    url: "{{ app__acme__tiny__download_upstream }}"
    owner: "root"
    group: "root"
    mode: "0755"
  when: ( acme_tiny__bin.stat.isreg is not defined or not acme_tiny__bin.stat.isreg ) and ( acme_tiny__usrbin.stat.isreg is not defined or not acme_tiny__usrbin.stat.isreg )

